### PR TITLE
Support keyword values as aliases for common translation keys

### PR DESCRIPTION
**Pull request by cjohansen**
As suggested in #8

### CODE REVIEW

**Comment by cjohansen** [comment]
Anything I can do to help this along?

**Comment by tonsky** [comment]
Sorry I just need to find a little time to do the review. Soon :)

**Comment by cjohansen** [comment]
Attempting a polite request for review on this :)

**Comment by mrijk** [comment]
Would love to have this as well. Anything I can do to help here?

**Comment by kirillsalykin** [comment]
any updates on this? :) soon takes a while it seems

**Comment by tonsky** [comment]
Sorry everyone, I’m embarassed how long it took me to get back to it. The PR is of fantastic quality, thank you @cjohansen! I didn’t have to change a thing.

Published 0.3.0 just now.

**Pull request closed without merging**
